client_id: 3MVG9QDx8IX8nP5R1mB17GH0oNymv0YcSL50HeFaOmfVHq2dr7GF5diJEgWEIf5lAf9DLoL4M_8Ot3zwfqty3
client_secret: 865733473786841267
username: laurent.de@tquila.com
password: tweedmungo12leU5RnpEj6bJh5RJxGh35zdX
host: login.salesforce.com
debugging: true